### ISSUE TITLE
Freezes when changing Game Directory

### ISSUE THREAD

**Issue by skyqrose** [Ipmake/kocitylauncher#21]
When I try to change the Game Directory, the launcher becomes unresponsive.
- I choose the new location in Windows Explorer, Explorer closes, and but the launcher never updates with the new path.
- Weirdly, the background still shifts around every few seconds.
- One time it did recover and I could interact with it again but then I tried changing the path again and it froze again. Not sure how to reproduce that though.

I ran through the command line and got a single log message when this happens:
```
{ canceled: false, filePaths: [ 'D:\\KnockoutCity' ] }
```
(`D:\\KnockoutCity` is the path I tried to choose.)

I was able to set the path once (before logging into Discord), and set it to `D:\\KnockoutCity\KnockoutCity-HighRes-10.0-269701` but it still said "Install" so I thought maybe I needed to change it again. But now it freezes every time I try. 

I was able to install and play by using the path that's stuck in the settings.

Relatedly: The README could use some instructions on how installing the game works, if you have to download it separately or if you have to download it through the launcher or either.

**Comment by Ipmake** [comment]
Fixed with https://github.com/Ipmake/kocitylauncher/releases/tag/v0.4.3-beta

@skyqrose, your installation is not in the proper format, point the launcher towards `D:\\KnockoutCity\` and rename `KnockoutCity-HighRes-10.0-269701` to just `highRes`
