### ISSUE TITLE
feature request: see server locations

### ISSUE THREAD

**Issue by skyqrose** [Ipmake/kocitylauncher#23]
It'd be useful to see in the server list where the servers are located.

- NinCollin's server (DummyCorps) is in the southeast US
- Gorndt's (TCNS) I think is hosted in Chicago, US

The others I don't know except for what's in the name.

Getting ping in the list is probably too much to ask and is not as important as just knowing the location.

While we're collecting more info about servers, it'd also be nice to have somewhere (the website maybe?) a list of servers, with a short description (and a discord link?) for each.

**Comment by Dentora** [comment]
Ko-na-west is Vancouver, CA

**Comment by MG-100** [comment]
Hos-DE-WE is Germany West

**Comment by skyqrose** [comment]
Devann from Dummy Corps requested that the launcher somehow link to their website:
https://discordapp.com/channels/803395866227507200/1086346121472905366/1116077385826185226
> nincollin has made a bit of a companion website to go along with our server, is there anyway you could link or refer to it on the launcher in some way? It displays a full list of players who have played on our server and statistics for each player

**Comment by Ipmake** [comment]
> While we're collecting more info about servers, it'd also be nice to have somewhere (the website maybe?) a list of servers, with a short description (and a discord link?) for each.

Yeah i already mentioned that, I will probably add that to the documentation

**Comment by skyqrose** [comment]
Ah, TCNS is in Lansing MI, not Chicago, which I found out like 10 minutes after hardcoding it in https://github.com/Ipmake/kocitydocs/pull/7

eh, close enough. :shrug: 

https://www.liquidweb.com/about-us/data-centers/
