### ISSUE TITLE
Opening the Launcher through Steam makes it unable to authenticate

### ISSUE THREAD

**Issue by EvanBG42** [Ipmake/kocitylauncher#24]
I am able to authenticate and launch the game when opening the launcher program. However, when opening the launcher from Steam, and attempting to join a server, it has the "attempting to authenticate" pop-up for a split second before disappearing, then the game does not launch.

**Comment by Ipmake** [comment]
Fixed with fd247fd
Published with https://github.com/Ipmake/kocitylauncher/releases/tag/v0.4.5-beta
