### ISSUE TITLE
Cannot read properties of null (reading 'write')

### ISSUE THREAD

**Issue by skyqrose** [Ipmake/kocitylauncher#25]
I've seen a couple people run across this:

```
Unexpected Error
An unexpected error occured. Error: Cannot read properties of null (reading 'write')
```

On Reddit: https://www.reddit.com/r/KnockoutCity/comments/142saw1/wanna_play_tonight_shoutout_to_the_communitymade/jn8nz92/

On Discord: https://discord.com/channels/1111747454564573346/1115240722489163776/1116309743712088095

And I've seen it at least once myself.

Ipmake says (at the discord link)
> You have discordRPC enabled in your settings but discord isn't running on your pc

We could handle this more gracefully and give a better warning message.

**Comment by Ipmake** [comment]
Fixed with 7275adb
https://github.com/Ipmake/kocitylauncher/releases/tag/v0.4.4-beta
